# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Open Artifacts Hub
email: jimappleg8@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  OpenArtifacts.com offers a way to find work that needs doing in the form of open projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jimappleg8
github_username:  jimappleg8

# It's handy to have the miscellaneous pages tucked into a folder
include: ['_pages']
paginate_path: "/_pages/index.html"

# The base theme of minima-reboot was integrated into this site, so it is
# no longer an external theme.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  
collections:
  projects:
    output: true
    permalink: /projects/:slug
  posts:
    output: true
    permalink: /posts/:slug

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - Jenkinsfile
  - minima-reboot.gemspec
  - Rakefile

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

footer_icons:
- username: jimappleg8/openartifacts-com/
  url: 'https://gitlab.com/jimappleg8/openartifacts-com'
  icon: gitlab-icon-rgb.svg

paginate: 5

markdown: kramdown

